def process_path(input_paths: list[str], exts: list[str]) -> list[str]: ...
def search_by_exts(input_paths: list[str], exts: list[str]) -> list[str]: ...
def search_by_regex(input_paths: list[str], regex_patterns: list[str]) -> list[str]: ...
